### ISSUE TITLE
sweetviz

### ISSUE THREAD

**Issue by nirjan-dev** [nirjan-dev/interesting-repos-tools-cheatsheets#273]
[link to the repo](https://github.com/fbdesignpro/sweetviz)

Sweetviz is an open source Python library that generates beautiful, high-density visualizations to kickstart EDA (Exploratory Data Analysis) with a single line of code. Output is a fully self-contained HTML application.

The system is built around quickly visualizing target values and comparing datasets. Its goal is to help quick analysis of target characteristics, training vs testing data, and other such data characterization tasks.

**Comment by Punya227** [comment]
i was getting some error like dataframe object error

**Comment by nirjan-dev** [comment]
@Punya227 unfortunately I haven't used this a lot so I can't help you but I would suggest opening an issue on their github repo
